export const gameList = [
  {
    title: "SRIDEVI MORNING",
    open: "09:25 AM",
    close: "10:25 AM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "LOTUS MORNING",
    open: "90:40 AM",
    close: "11:40 AM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "KARNATAKA DAY",
    open: "10:00 AM",
    close: "11:00 AM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MILAN MORNING",
    open: "10:00 AM",
    close: "11:00 AM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "ROYAL KALYAN MORNING",
    open: "10:40 AM",
    close: "11:40 AM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "KALYAN MORNING",
    open: "11:00 AM",
    close: "12:00 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "SRIDEVI",
    open: "11:15 AM",
    close: "12:15 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MADHUR MORNING",
    open: "11:15 AM",
    close: "12:15 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "TIME BAZAR",
    open: "01:00 PM",
    close: "02:00 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MADHUR DAY",
    open: "1:20 PM",
    close: "2:20 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "LOTUS DAY",
    open: "02:30 PM",
    close: "04:30 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "ROYAL KALYAN DAY",
    open: "02:40 PM",
    close: "03:40 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MILAN DAY",
    open: "02:50 PM",
    close: "04:50 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "RAJDHANI DAY",
    open: "02:55 PM",
    close: "04:55 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "SUPREME DAY",
    open: "03:25 PM",
    close: "05:25 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "KALYAN",
    open: "03:35 PM",
    close: "05:35 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "LOTUS NIGHT",
    open: "06:20 PM",
    close: "09:20 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "KARNATKA NIGHT",
    open: "06:40 PM",
    close: "07:40 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "SRIDEVI NIGHT",
    open: "07:00 PM",
    close: "08:00 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MADHUR NIGHT",
    open: "08:20 PM",
    close: "10:20 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "SUPREME NIGHT",
    open: "08:30 PM",
    close: "10:30 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "ROYAL KALYAN NIGHT",
    open: "08:40 PM",
    close: "10:40 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MILAN NIGHT",
    open: "08:55 PM",
    close: "10:55 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "KALYAN NIGHT",
    open: "9:25 PM",
    close: "10:55 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "RAJDHANI NIGHT",
    open: "09:30 PM",
    close: "11:45 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
  {
    title: "MAIN BAZAR",
    open: "09:55 PM",
    close: "11:58 PM",
    digit: "XXX-XX-XX",
    chartLink: "panel/chart",
  },
];

export const options = [
  {
    title: "Single Digit",
    link: "someLink",
  },
  {
    title: "Jodi Digit",
    link: "someLink",
  },
  {
    title: "Single Panna",
    link: "someLink",
  },
  {
    title: "Double Panna",
    link: "someLink",
  },
  {
    title: "Triple Panna",
    link: "someLink",
  },
  {
    title: "Half Sangam",
    link: "someLink",
  },
  {
    title: "Full Sangam",
    link: "someLink",
  },
  {
    title: "SPDPTP",
    link: "someLink",
  },
];
